### ISSUE TITLE
Where is the jsglue.js?

### ISSUE THREAD

**Issue by eshijia** [stewartpark/Flask-JSGlue#13]
I found the module need a javascript file called `jsglue.js`, but where should I get that file?

**Comment by bladeoflight16** [comment]
`jsglue.js` is generated in the [`flask_jsglue.py`](https://github.com/stewartpark/Flask-JSGlue/blob/master/flask_jsglue.py) module. Look at the `generate_js` if you want to see the source. It's made available in the application by adding a route to a `Flask` object, which causes it to be generated on the fly.

If you're getting errors about it being missing, though, I'm betting you didn't do the initial set up correctly. As indicate by [the docs](http://stewartjpark.com/Flask-JSGlue/), you need to initialize it when you initialize the `Flask` object. You do this one of two ways:

 1. Call `init_app`:

    ```
    from flask import Flask
    from flask_jsglue import JSGlue

    app = Flask(__name__)
    jsglue = JSGlue()
    jsglue.init_app(app)
    ```

    or

 1. Pass the `Flask` object to the `JSGlue` initializer:

    ```
    from flask import Flask
    from flask_jsglue import JSGlue
    
    app = Flask(__name__)
    jsglue = JSGlue(app)
    ```
