### ISSUE TITLE
Make generate_js more flexible

### ISSUE THREAD

**Issue by imaia** [stewartpark/Flask-JSGlue#17]
Maybe put it into a template that can be overwritten.

**Comment by stewartpark** [comment]
That's also a great idea. I'll take that idea into consideration in solving the below issue:

https://github.com/stewartpark/Flask-JSGlue/issues/18

**Comment by italomaia** [comment]
Fair. I did this PR for this very functionality. https://github.com/stewartpark/Flask-JSGlue/pull/19

**Comment by rlam3** [comment]
@stewartpark Any updates on this release?

**Comment by stewartpark** [comment]
This was fixed by this: https://github.com/stewartpark/Flask-JSGlue/pull/19
