### ISSUE TITLE
production does not see jsglue...

### ISSUE THREAD

**Issue by rlam3** [stewartpark/Flask-JSGlue#18]
serving flask app on uwsgi and nginx for static files does not enable jsglue to work properly... 
any reason why jsglue isn't being found? 

is jsglue only good for development and not for production use?

**Comment by stewartpark** [comment]
Looks like this becomes a hard problem for the current release of JSGlue when the assets server resides somewhere else or the reverse proxy has a different URI mounted to the server.

I'll see if I can make a fix for this tonight. Thanks for reporting this.

**Comment by rlam3** [comment]
@stewartpark Thanks! Was wondering on the progress on this issue.

**Comment by stewartpark** [comment]
Though this thread has much better history of explaining the problem, I think the actual action item should be this one: https://github.com/stewartpark/Flask-JSGlue/issues/15
I'll close this and try to make some time to work on this!
