### ISSUE TITLE
Note werkzeug recommendation against javascript routing

### ISSUE THREAD

**Issue by fuhrysteve** [stewartpark/Flask-JSGlue#7]
Something to consider:

This functionality is built into werkzeug, however it is depreciated:
https://github.com/mitsuhiko/werkzeug/blob/master/werkzeug/contrib/jsrouting.py

See:
http://werkzeug.pocoo.org/docs/0.10/transition/#stop-using-deprecated-things

**Comment by stewartpark** [comment]
Hi fuhrysteve,

If I'm understanding the matter correctly, it seems like it mostly has to do with scaling. I can see a few possible issues when the backend pieces are compartmentalized and the presentation layer has a different URL routing policy. i.e. multi-tier architecture.

I've been getting some concerns related to public routing, and admittedly I haven't thought of those cases when I was building this. But I think I can provide some options to work around the case, and I believe this extension still can be a valid option for small projects.

Thanks for the input!

Best,
Stewart
